AWSTemplateFormatVersion: "2010-09-09"

Parameters: 
  Stage:
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - qa
      - demo
      - prod
  ProjectName:
    Type: String
  
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Stage}-buckets3-${ProjectName}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "input/customers/"
                  - Name: suffix
                    Value: .csv
            Function: !GetAtt LambdaCrawlerFunction.Arn
    DependsOn:
      - LambdaCrawlerPermission
  
  LambdaCrawlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Stage}-lambda-crawler-trigger-${ProjectName}
      Code: lambdaCode
      Handler: app.lambda_handler
      Runtime: python3.9
      Description: serverless lambda to trigger glue crawler
      Timeout: 30
      Environment:
        Variables:
          TRIGGER: !Ref glueCrawlerCSVTrigger
      Role: !GetAtt LambdaCrawlerRole.Arn

  LambdaCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Stage}-lambda-function-role-${ProjectName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: !Sub ${Stage}-lambda-function-policy-${ProjectName}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub arn:aws:s3:::${Stage}-buckets3-${ProjectName}/*
                - !Sub arn:aws:s3:::${Stage}-buckets3-${ProjectName}
            - Effect: Allow
              Action: glue:StartTrigger
              Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:trigger/*
            - Effect: Allow
              Action: glue:ListTriggers
              Resource: "*"
        
  LambdaCrawlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaCrawlerFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:${AWS::Partition}:s3:::${Stage}-buckets3-${ProjectName}"

  glueInputDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: input

  glueOutputDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: output

  glueCSVCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub ${Stage}-csv-crawler-${ProjectName}
      Role: !GetAtt glueRole.Arn
      Description: Glue crawler for customer data
      DatabaseName: !Ref glueInputDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${Stage}-buckets3-${ProjectName}/input/customers
            Exclusions: []
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DELETE_FROM_DATABASE
      Configuration: |
        {
          "Version":1.0,
          "CrawlerOutput":{
            "Partitions":{
              "AddOrUpdateBehavior":"InheritFromTable"
            },
            "Tables":{
              "AddOrUpdateBehavior":"MergeNewColumns"
            }
          },
          "Grouping":{
            "TableGroupingPolicy":"CombineCompatibleSchemas"
          }
        }
      TablePrefix: csv_

  glueParquetCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub ${Stage}-parquet-crawler-${ProjectName}
      Role: !GetAtt glueRole.Arn
      Description: Glue crawler for customer data
      DatabaseName: !Ref glueOutputDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${Stage}-buckets3-${ProjectName}/output/customers
            Exclusions: []
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DELETE_FROM_DATABASE
      Configuration: |
        {
          "Version":1.0,
          "CrawlerOutput":{
            "Partitions":{
              "AddOrUpdateBehavior":"InheritFromTable"
            },
            "Tables":{
              "AddOrUpdateBehavior":"MergeNewColumns"
            }
          },
          "Grouping":{
            "TableGroupingPolicy":"CombineCompatibleSchemas"
          }
        }
      TablePrefix: parquet_

  glueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Stage}-glue-role-${ProjectName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: glue.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
      - PolicyName: !Sub ${Stage}-glue-bucket-policy-${ProjectName}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub arn:aws:s3:::${Stage}-buckets3-${ProjectName}/*
                - !Sub arn:aws:s3:::${Stage}-buckets3-${ProjectName}
      - PolicyName: !Sub ${Stage}-glue-scripts-policy-${ProjectName}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
              Resource:
                - !ImportValue 
                  'Fn::Sub': ${Stage}-jenkins-onboarding-assets-bucket
                - !Join
                  - ''
                  - - !ImportValue 
                        'Fn::Sub': ${Stage}-jenkins-onboarding-assets-bucket
                    - "/*"
      - PolicyName: !Sub ${Stage}-glue-Database-policy-${ProjectName}
        PolicyDocument: 
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - glue:Update*
                - glue:Create*
                - glue:Import*
              Resource: 
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${glueInputDatabase}
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${glueOutputDatabase}
      - PolicyName: !Sub ${Stage}-glue-table-policy-${ProjectName}
        PolicyDocument: 
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - glue:Update*
                - glue:Create*
                - glue:Import*
              Resource: 
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${glueInputDatabase}
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${glueOutputDatabase}
      - PolicyName: !Sub ${Stage}-glue-logs-policy-${ProjectName}
        PolicyDocument: 
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  
  glueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !Ref glueRole
      Command:
        Name: glueetl
        ScriptLocation: glueScript/script.py
      Description: convert csv to parquet
      GlueVersion: '3.0'
      MaxCapacity: 10
      MaxRetries: 0
      Name: !Sub ${Stage}-glue-job-${ProjectName}
      DefaultArguments:
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-continuous-log-filter": "true"
        "--enable-metrics": "true"
        "--output_path": !Sub "s3://${Stage}-buckets3-${ProjectName}/output/customers"

  glueCrawlerCSVTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub ${Stage}-start-workflow-crawler-csv-trigger-${ProjectName}
      Type: ON_DEMAND
      Actions:
        - CrawlerName: !Ref glueCSVCrawler
      WorkflowName: !Ref glueWorkflow

  glueJobCSVParquetTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub ${Stage}-glue-job-trigger-${ProjectName}
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - JobName: !Ref glueJob
      Predicate:
        Conditions:
          - CrawlerName: !Ref glueCSVCrawler
            LogicalOperator: EQUALS
            CrawlState: SUCCEEDED
      WorkflowName: !Ref glueWorkflow
  
  glueCrawlerParquetTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub ${Stage}-crawler-parquet-trigger-${ProjectName}
      Type: CONDITIONAL
      StartOnCreation: true
      Actions:
        - CrawlerName: !Ref glueParquetCrawler
      Predicate:
        Conditions:
          - JobName: !Ref glueJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
      WorkflowName: !Ref glueWorkflow

  glueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: GlueWorkflow pipeline 
      Name: !Sub ${Stage}-glue-workflow2-${ProjectName}

Outputs:
  s3Bucket:
    Description: The name of the bucket
    Value: !Ref s3Bucket